FROM base AS builder
WORKDIR /app

ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_APP_URL

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# TESTE DAS VARIÁVEIS
RUN test -n "$NEXT_PUBLIC_FIREBASE_API_KEY" || (echo "ERRO: FIREBASE_API_KEY não chegou" && exit 1)
RUN test -n "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" || (echo "ERRO: FIREBASE_AUTH_DOMAIN não chegou" && exit 1)
RUN test -n "$NEXT_PUBLIC_FIREBASE_PROJECT_ID" || (echo "ERRO: FIREBASE_PROJECT_ID não chegou" && exit 1)
RUN test -n "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" || (echo "ERRO: STORAGE_BUCKET não chegou" && exit 1)
RUN test -n "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" || (echo "ERRO: SENDER_ID não chegou" && exit 1)
RUN test -n "$NEXT_PUBLIC_FIREBASE_APP_ID" || (echo "ERRO: FIREBASE_APP_ID não chegou" && exit 1)

RUN npm run build